#!/bin/sh
### BEGIN INIT INFO
# Provides:          thin
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      S 0 1 6
# Short-Description: thin initscript
# Description:       thin
### END INIT INFO

# Original author: Forrest Robertson

# Do NOT "set -e"

# Changes by Gregory Mostizky
# Instead of running thin for all configurations, we run thin for each configuration separately.
# We also take care to load proper RVM environment (defined in $app_home/config.rvm) as well as bundle
# All application folders are defined in /etc/thin/apps.conf file

RVM=/usr/local/rvm
SCRIPT_NAME=/etc/init.d/thin
CONFIG_PATH=/etc/thin

# Exit if the package is not installed
#[ -x "thin" ] || exit 0

case "$1" in
  start)
	for app in `cat $CONFIG_PATH/apps.conf`; do cd $app && source "$RVM/environments/`cat config.rvm`" && bundle exec thin start --config $app/thin.yaml; done
	;;
  stop)
        for app in `cat $CONFIG_PATH/apps.conf`; do cd $app && source "$RVM/environments/`cat config.rvm`" && bundle exec thin stop --config $app/thin.yaml; done
	;;
  restart)
          for app in `cat $CONFIG_PATH/apps.conf`; do cd $app && source "$RVM/environments/`cat config.rvm`" && bundle exec thin restart --config $app/thin.yaml; done
	;;
  *)
	echo "Usage: $SCRIPT_NAME {start|stop|restart}" >&2
	exit 3
	;;
esac
