#!/bin/sh
### BEGIN INIT INFO
# Provides:          thin
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      S 0 1 6
# Short-Description: thin initscript
# Description:       thin
### END INIT INFO

# Original author: Forrest Robertson

# Do NOT "set -e"

BUNDLE=/usr/local/bin/bundle
DAEMON=/usr/local/bin/thin
SCRIPT_NAME=/etc/init.d/thin
CONFIG_PATH=/etc/thin

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

case "$1" in
  start)
        #$DAEMON start --all $CONFIG_PATH
        for app in `cat /etc/thin/apps.conf`; do cd $app && $BUNDLE exec $DAEMON start --config $app/thin.yaml; done
        ;;
  stop)
        #$DAEMON stop --all $CONFIG_PATH
        for app in `cat /etc/thin/apps.conf`; do cd $app && $BUNDLE exec $DAEMON stop --config $app/thin.yaml; done
        ;;
  restart)
        #$DAEMON restart --all $CONFIG_PATH
        for app in `cat /etc/thin/apps.conf`; do cd $app && $BUNDLE exec $DAEMON restart --config $app/thin.yaml; done
        ;;
  *)
        echo "Usage: $SCRIPT_NAME {start|stop|restart}" >&2
        exit 3
        ;;
esac